# 3.2 Tensors: Multidimensional arrays

### 3.2.1 From Python lists to PyTorch tensors

In [2]:
import torch
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [3]:
a[1]

tensor(1.)

In [4]:
float(a[1])

1.0

In [5]:
a[2] = 2.0
a

tensor([1., 1., 2.])

### 3.2.3 The essence of tensors

In [6]:
points = torch.zeros(6)
points

tensor([0., 0., 0., 0., 0., 0.])

In [7]:
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [8]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [9]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [10]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [11]:
points.shape

torch.Size([3, 2])

In [12]:
points = torch.zeros(3,2)   
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [13]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [14]:
points[0, 1]

tensor(1.)

In [15]:
points[0]

tensor([4., 1.])

### 3.3 Indexing tensors

In [16]:
some_list = list(range(6))  
print(some_list[:])
print(some_list[1:4])
print(some_list[1:])
print(some_list[:4])
print(some_list[:-1])
print(some_list[1:4:2])

[0, 1, 2, 3, 4, 5]
[1, 2, 3]
[1, 2, 3, 4, 5]
[0, 1, 2, 3]
[0, 1, 2, 3, 4]
[1, 3]


In [17]:
print(points)
print(points[1:])
print(points[1:, :])
print(points[1:, 0])
print(points[None])

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])
tensor([[5., 3.],
        [2., 1.]])
tensor([[5., 3.],
        [2., 1.]])
tensor([5., 2.])
tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])


### 3.4 Broadcasting

### Named tensors

In [18]:
img_t = torch.randn(3, 5, 5)
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [19]:
batch_t = torch.randn(2, 3, 5, 5)

In [20]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [21]:

unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
img_weights = img_t * unsqueezed_weights
batch_weights = batch_t * unsqueezed_weights
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape



(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [22]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

/var/folders/8f/4rsnf6756kj3wm0sqfr9xyfc0000gn/T/ipykernel_25033/2371314847.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/c10/core/TensorImpl.h:1976.)
  weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [23]:
img_named =  img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [24]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [25]:
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names


(torch.Size([5, 5]), ('rows', 'columns'))

## Managing a tensor's datatype attribute

### 1. Set a dtype when creating a tensor
### 2. Read a tensor's datatype.
### 3. Convert a tensor to a different dtype.
### 4. Predict what dype results from mixing two dtypes in an operation.

In [26]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [27]:
short_points.dtype

torch.int16

In [28]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [29]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [30]:
points_64 = torch.rand(5, dtype=torch.double)
points_short = points_64.to(torch.short)
points_64 * points_short

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

## 3.7 The tensor API

In [31]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [32]:
a = torch.ones(3,2)
a_t = a.transpose(0, 1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

### 3.8.1 Indexing into storage

In [33]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

/var/folders/8f/4rsnf6756kj3wm0sqfr9xyfc0000gn/T/ipykernel_25033/2923139482.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [34]:
points_storage = points.storage()
points_storage[0]

4.0

In [35]:
points.storage()[1]

1.0

In [36]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points


tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

### 3.8.2 Modifying stored values: In-place operations

In [37]:
a = torch.ones(3, 2)
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

### 3.9.1 Views of another tensor's storage

In [58]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
print(second_point.storage_offset())

2


In [40]:
second_point.size()

torch.Size([2])

In [42]:
second_point.shape

torch.Size([2])

In [59]:
points.stride()

(2, 1)

In [60]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [61]:
second_point.storage_offset()

2

In [62]:
second_point.stride()

(1,)

In [63]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points


tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [64]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

### 3.9.2 Transposing without copying

In [65]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [66]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [67]:
id(points.storage()) == id(points_t.storage())

True

In [68]:
points.stride()

(2, 1)

In [70]:
points_t.stride()

(1, 2)

### 3.9.3 Transposing to higher dimensions

In [94]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [95]:
transpose_t.shape

torch.Size([5, 4, 3])

In [96]:
some_t.stride()

(20, 5, 1)

In [97]:
transpose_t.stride()

(1, 5, 20)

### 3.9.4 Contigous tensors

In [98]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])


In [99]:
points.is_contiguous()

True

In [100]:
point_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [101]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [102]:
points_t.stride()

(1, 2)

In [103]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [ ]:
points_t_cont.stride()

(3, 1)

In [107]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

### 3.10.1 Managing a tensor's device attribute

In [109]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='mps')

In [113]:
points_gpu = points.to(device='mps')

### 3.11 NumPy interoperability

In [114]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [115]:
points = torch.from_numpy(points_np)

### 3.13 Serializing tensor

## Exercise

### Question 1

In [130]:
a = torch.tensor(list(range(9)))

print(a)
print(a.shape)
print(a.storage_offset())
print(a.stride())
print(a.dtype)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
torch.Size([9])
0
(1,)
torch.int64


In [133]:
b = a.view(3,3)

In [135]:
print(b)
print(b.shape)
print(b.storage_offset())
print(b.stride())
print(b.dtype)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
torch.Size([3, 3])
0
(3, 1)
torch.int64


In [134]:
id(b.storage()) == id(a.storage())

True

In [137]:
c = b[1:, 1:]
print(c)
print(c.shape)
print(c.storage_offset())
print(c.stride())
print(c.dtype)

tensor([[4, 5],
        [7, 8]])
torch.Size([2, 2])
4
(3, 1)
torch.int64


### Question 2

In [139]:
torch.sqrt(a)

tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284])

In [143]:
result = torch.sqrt(a)
print(result.dtype)
print(a.dtype)
a = a.float()
a.sqrt_()
print(a)

torch.float32
torch.float32
tensor([0.0000, 1.0000, 1.0905, 1.1472, 1.1892, 1.2228, 1.2510, 1.2754, 1.2968])
